### ISSUE TITLE
processGolay.py

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteCaller#14]
out_handle = open("Data/correctedI1-" + fileNumber + ".fasta","a")

a: append mode. It should start from fresh. Reads will duplicate if a run was not successfully processed by the pipeline in a single time, and the folder was not cleaned before more attempts. Duplicated reads leads to duplicated read names and will result in an error later.

Suggested change:
outfile = ( "Data/correctedI1-" + fileNumber + ".fasta" )
os.remove(outfile) if os.path.exists(outfile) else None
out_handle = open(outfile, "a")

**Comment by anatolydryga** [comment]
or should we just require the clean folder structure and fail
if folder has anything else except required Data, sampleInfo.tsv?
