### ISSUE TITLE
Frances's Was run

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteCaller#17]
Seems to be OK. Some concerns:

```
[yinghua@node063 run20150505]$ grep -i exit logs/*
## clean

[yinghua@node063 run20150505]$ grep -i error logs/*
logs/callSitesOutput3.txt:[1] "Caught error: error in evaluating the argument 'f' in selecting a method for function 'split': Error in as.vector(Rle(pairedAlignments$pairingID, alignmentsPerPairing)) : \n  error in evaluating the argument 'x' in selecting a method for function 'as.vector': Error in (function (classes, fdef, mtable)  : \n  unable to find an inherited method for function ‘Rle’ for signature ‘\"integer\", \"list\"’\nCalls: Rle -> <Anonymous>\n"
... ...
logs/errorCorrectWorkerOutput9.txt:/home/yinghua/intSiteCaller/errorCorrectIndices/golay.py:74: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
logs/trimOutput1.txt:[1] "Caught error: error - no curated reads"
logs/trimOutput2.txt:[1] "Caught error: error - no curated reads"
logs/trimOutput4.txt:[1] "Caught ERROR in intSiteLogic: No hits found which passed the qualityThreshold"
logs/trimOutput4.txt:[1] "Caught ERROR in intSiteLogic: No hits found"
logs/trimOutput4.txt:[1] "Caught error: error - no curated reads"
```

no curated reads, no hits were due to UninfectedControls-1,2,3,4.

**Comment by esherm** [comment]
That's actually an excellent result!  The uninflected controls should produce no valid integration sites. We include an uninfected control in every run to confirm that we don't see crossover from real patient samples (that should have integration sites) into a known negative control that should **not** have integration sites.

**Comment by yhwu** [comment]
Eric, take it easy! Enjoy your time off! I hope you are not driving and texting:)

**Comment by anatolydryga** [comment]
Should we still create entry in DB for the sample?

that would help to understand if sample is processed vs sample 
that is not processed, so we have cases:
1. processed - no sites
2. not processed
3. processed - there are sites

?

**Comment by yhwu** [comment]
That's certainly necessary. Let's discuss with everyone when you come back.

**Comment by anatolydryga** [comment]
ok keeping the issue open...
