### ISSUE TITLE
intSiteCaller seems to hang, although RData objects were created.

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteCaller#2]
981538  yinghua PEND  normal     node027.hpc             *alidation May 27 10:24
997253  yinghua PEND  normal     node088.hpc             *alidation May 28 13:55

[yinghua@node063 intSiteValidation]$ ls -l clone1-1/
total 384
-rw-rw-r-- 1 yinghua yinghua  1232 May 28 14:31 allSites.RData
-rw-rw-r-- 1 yinghua yinghua    61 May 28 14:31 callStatus.RData
-rw-rw-r-- 1 yinghua yinghua  1184 May 28 14:31 chimeraData.RData
-rw-rw-r-- 1 yinghua yinghua  1415 May 28 14:31 hits.R1.RData
-rw-rw-r-- 1 yinghua yinghua  1310 May 28 14:31 hits.R2.RData
-rw-rw-r-- 1 yinghua yinghua   487 May 28 14:27 keys.RData
-rw-rw-r-- 1 yinghua yinghua  1165 May 28 14:31 multihitData.RData
-rw-rw-r-- 1 yinghua yinghua 14509 May 28 14:27 primerIDData.RData
-rw-rw-r-- 1 yinghua yinghua  3108 May 28 14:27 R1-1.fa
-rw-rw-r-- 1 yinghua yinghua   494 May 28 14:31 R1-1.fa.psl.gz
-rw-rw-r-- 1 yinghua yinghua  1284 May 28 14:27 R2-1.fa
-rw-rw-r-- 1 yinghua yinghua   242 May 28 14:31 R2-1.fa.psl.gz
-rw-rw-r-- 1 yinghua yinghua   832 May 28 14:31 sites.final.RData
-rw-rw-r-- 1 yinghua yinghua   385 May 28 14:31 stats.RData
-rw-rw-r-- 1 yinghua yinghua    73 May 28 14:27 trimStatus.RData

**Comment by esherm** [comment]
Pretty sure this was resolved with f89355265d041ada4aa5a3524db78d53516fe732 

Make sure you have the most recent version of code and try it again

**Comment by yhwu** [comment]
Clean exit!
