### ISSUE TITLE
fix_seg branch 

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteCaller#21]
Some difference for "-" strand rows, "+" strand rows seem to be identical

```
24    chr17 18145962 18146337   376      - 11, 12         6   clone1-4  D03FP:1:1101:16257:9296
24    chr17 18145962 18145962     1      - 11, 12         6   clone1-4  D03FP:1:1101:16257:9296
```

This is possibly caused by

```
# in chris's fix
standardizedStarts <- rep(start(dereplicated), dereplicated$counts)

# in original
standardizedStarts <- start(flank(standardized, -1, start=T))
standardized <- unname(dereplicated[rep(dereplicated$dereplicatedSiteID, dereplicated$counts)])
```

A possible fix to chris' could be 

```
standardizedStarts <- rep(start(flank(dereplicated, -1, start=T)), dereplicated$counts)
```

**Comment by anatolydryga** [comment]
yes, the flank -1 hack is essential,

if possible fix passes acceptance test - than we can just use it,
because we not gonna change the external behavior

**Comment by yhwu** [comment]
Passed intSiteValition test; will do Frances' run and compare later.

**Comment by anatolydryga** [comment]
if it passes validation,
we can just accept it...
the whole idea of the acceptance test that it checks behavior 
and we don't need to run something else(well, unless we have a bug in acceptance test)

**Comment by yhwu** [comment]
The intSiteValition test has too few reads. Exposure to exceptions is very limited.

**Comment by yhwu** [comment]
Generated the same md5 for Frances' run20150505.
