### ISSUE TITLE
***top priority, UninfectedControls-1, names for control should have runid in it, 

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteCaller#26]
something like UninfectedControls150218-1

**Comment by cnobles** [comment]
That would allow us to distinguish each UninfectedControl and NoTemplateControl from each other. This would be required if we upload these sites into the DB, are we?

**Comment by anatolydryga** [comment]
yes this is for DB, the problem with it that we don't know that numbers before

**Comment by anatolydryga** [comment]
not in the database yet
