### ISSUE TITLE
***deal with re-dos on the same GTSPs 

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteCaller#27]
for example, 

```
run20150505 GTSP0308
run20150218 GTSP0308
```

**Comment by cnobles** [comment]
I think we had decided that the replicates would just continue in sequential order. So the four replicates on run20150218 for GTSP0308 would be: GTSP0308-1, GTSP0308-2, GTSP0308-3, GTSP0308-4, then the replicates on run20150505  would be GTSP0308-5, GTSP0308-6, GTSP0308-7, GTSP0308-8. Does this work?

**Comment by yhwu** [comment]
This should work. So, before we process a sampleinfo.csv, we should check whether the setnames are already in the database. If they are, we will modify the sampleinfo.csv manually.

**Comment by anatolydryga** [comment]
check is good idea, but it should be separate script not part of caller... which only call sites
and should not know anything about DB or downstream
