### ISSUE TITLE
check_stats.R crashes on unfinished run

### ISSUE THREAD

**Issue by cnobles** [BushmanLab/intSiteCaller#29]
Tried running check_stats.R on runs which don't have 100% completion (about 95% or more samples completed) and the error message below is returned:

Error in rbind(deparse.level, ...) :
  numbers of columns of arguments do not match
Calls: do.call -> <Anonymous> -> rbind
Execution halted

I'm going to take a guess at the issue: since not all the samples finished, the stats.RData from each of the samples don't have the same number of columns and therefore cannot rbind().

**Comment by yhwu** [comment]
git pull and try again

**Comment by cnobles** [comment]
That worked, my bad. Anyway we could make the stats more human readable?

**Comment by yhwu** [comment]
Some bar plots would be good.

**Comment by cnobles** [comment]
I output the files to tsv and transferred them to my comp to view in excel. Maybe next time change them to csv's and make my life easier.

**Comment by yhwu** [comment]
```
Rscript check_stat.R | tr "\t" "," > tmp.csv
```

**Comment by cnobles** [comment]
Ok, I was going to use sed , but I like learning to use new functions! Thanks Yinghua.
