### ISSUE TITLE
Dereplicating and Clustering sites may result in up stream shift of 5bp or more. 

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteCaller#30]
Dereplicating and standardizing sites is based on reduce instead of overlap.

**Comment by anatolydryga** [comment]
reduce itself is based on overlap(?)
 see 
http://www.bioconductor.org/packages/release/bioc/vignettes/GenomicRanges/inst/doc/GenomicRangesIntroduction.pdf

p.8 last paragraph

the integration site is always the start or end of overlapping region
(as investigated by @cnobles )

note that is different how it is handled in "old" pipeline
