### ISSUE TITLE
Correcting barcode results in 20% loss of reads. Too much.

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteCaller#36]

**Comment by esherm** [comment]
This is likely due to the PhiX spike. The unbarcoded PhiX reads end up being assigned phony low-quality barcodes which cannot be error corrected.  We aim for a 15-20% PhiX spike which interestingly is the same percentage of reads that we're seeing fail to error correct.

**Comment by yhwu** [comment]
Interesting.

**Comment by esherm** [comment]
To test this, try finding the R1/R2 sequences that correspond to barcodes that failed error-correction and align them to PhiX. The vast majority (90%+ if memory serves) will have a near perfect alignment.

**Comment by yhwu** [comment]
Thanks for the tip!
