### ISSUE TITLE
parallel demultiplexing

### ISSUE THREAD

**Issue by anatolydryga** [BushmanLab/intSiteCaller#41]
#Demultiplexing is currently a single-core process - perhaps it could be made
  #more efficient by having each error-correct worker do its own
  #mini-demultiplex with the barcodes that it error corrected, then write their
  #own shorter fastq files which can be cat'd together after everything is done

**Comment by aubreybailey** [comment]
Demultiplexing takes ~15 minutes and is likely limited by disk speed, not processing.
