### ISSUE TITLE
Columns from technicians

### ISSUE THREAD

**Issue by yhwu** [BushmanLab/intSiteCaller#6]
alias, linkerSequence, bcSeq, gender, primer    , ltrBit, largeLTRFrag, vectorSeq
1. column names are case sensitive.
2. barcode and alias should have unique relationship.
3. alias should be something like GTSP0001-1 for gene therapy.

**Comment by anatolydryga** [comment]
fix a8443c58c490b33ce69b64a1fd7b10e6aa929468

**Comment by anatolydryga** [comment]
alias is not enforced here, will be enforced in Uploader
