### ISSUE TITLE
concept of a trial should be intoduced

### ISSUE THREAD

**Issue by anatolydryga** [BushmanLab/intSiteCaller#8]
if we have concept of the run many parameters could be pulled from elsewhere:

primer
lltrBit
largLTRFrag
vectorSeq
reference Genome

**Comment by esherm** [comment]
Good idea!

Careful about including the reference genome in the "trial", as we may want to re-process the same samples with multiple different reference genomes, depending on what other samples we want compare to

**Comment by anatolydryga** [comment]
agreed! ref genome is a 'dry side' feature
